## Welcome to Numpy Tutorial

In [45]:
import numpy as np

## Array

In [46]:
## Creating Array
arr = np.array([9,0,2,1])
print("Array :",arr)

Array : [9 0 2 1]


In [47]:
arrr = np.array([1.0,2.5,5.7])
print("Array :",arrr)

Array : [1.  2.5 5.7]


In [48]:
ar=([0,2,4],[1,3,5],[6,8,7])
array=np.array(ar)
print("Your array is :",array)

Your array is : [[0 2 4]
 [1 3 5]
 [6 8 7]]


In [49]:
## Different types
a = [1, 2, 3, 4, 5]
b = (33, 55, 33, 22, 44)
c = ('1', '2', '3')
d = "Hello World"

In [50]:
print(a)
print(b)
print(c)
print(d)

[1, 2, 3, 4, 5]
(33, 55, 33, 22, 44)
('1', '2', '3')
Hello World


In [51]:
## 1-D Array
a = [1, 2, 3, 4, 5]
print("1-D array:",a)

1-D array: [1, 2, 3, 4, 5]


In [52]:
## 2-D Array
ar=  [[8,8,8,8], [52,41,26,95]]
var = np.array(ar,dtype=int)
print("2-D array:",var)


2-D array: [[ 8  8  8  8]
 [52 41 26 95]]


## Array Creation

In [53]:
## Diffrent Ways to Create Array


In [58]:
## using arrange
arr=np.arange(1,20)
print("The numbers are arrange from 1 to 20:",arr)

The numbers are arrange from 1 to 20: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [59]:
arr=np.arange(10)
print("The numbers are arrange till 10:",arr)

The numbers are arrange till 10: [0 1 2 3 4 5 6 7 8 9]


In [61]:
arr=np.arange(5,10,dtype=float)
print("The numbers are arrange till 10:",arr)

The numbers are arrange till 10: [5. 6. 7. 8. 9.]


In [71]:
## using linspace
lin=np.linspace(1,10,5,retstep=True)
print("It will print no. from 1 to 10 with equal distribution:",lin)

It will print no. from 1 to 10 with equal distribution: (array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ]), 2.25)


In [72]:
np.zeros([3,2])

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [77]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [79]:
np.full([4,3], 10)


array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [82]:
np.full(10,"NP",dtype=object)

array(['NP', 'NP', 'NP', 'NP', 'NP', 'NP', 'NP', 'NP', 'NP', 'NP'],
      dtype=object)

In [84]:
 np.full([3,3], 'np')

array([['np', 'np', 'np'],
       ['np', 'np', 'np'],
       ['np', 'np', 'np']], dtype='<U2')

## 2-D Array Creation

In [85]:
## using eye
arr=np.eye(3)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [88]:
arr=np.eye(5,5)
print(arr)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [90]:
## using diagonal
np.diag([9,0,2])


array([[9, 0, 0],
       [0, 0, 0],
       [0, 0, 2]])

In [91]:
## Basic Attributes

In [92]:
a = np.array([1, 2, 3, 4, 5, 6])
b = a.reshape((2, 3))
print("The reshape attribute:",b)

The reshape attribute: [[1 2 3]
 [4 5 6]]


In [94]:
a = np.array([11, 22, 33, 44])
b = np.resize(a, (3, 4))
print("The Rezsize attribute:",b)

The Rezsize attribute: [[11 22 33 44]
 [11 22 33 44]
 [11 22 33 44]]


In [99]:
a = np.array([1, 2,5])
b = np.tile(a, [2,2])
print("The Tile attribute:",b)

The Tile attribute: [[1 2 5 1 2 5]
 [1 2 5 1 2 5]]


In [105]:
b=4,5
c = np.repeat(b,3)
print("The repeat attribute:",c)

The repeat attribute: [4 4 4 5 5 5]


In [107]:
a = np.array([[11, 12, 13], [4, 5, 6]])
print("The ndim attribute is :",a.ndim)

The ndim attribute is : 2


In [109]:
a = np.array([[9,0,2,1,8], [0,2,9,0,0]])
print("The Flatten attribute:",a.flatten())

The Flatten attribute: [9 0 2 1 8 0 2 9 0 0]


In [110]:
a = np.arange(0, 10, 2)
print(a)

[0 2 4 6 8]
